# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x
    - name: Build
      run: dotnet publish -c Release -p:PublishSingleFile=true --self-contained true
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        path: src/bin/Release/net10.0/linux-x64/publish
